# Generated by Django 5.2 on 2026-09-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_keyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='encryption_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='iv',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='encrypted_files/'),
        ),
    ]
