# Generated by Django 5.2 on 2026-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_uploadedfile_encryption_key_uploadedfile_iv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
